In [1]:
import pandas as pd
df = pd.DataFrame({'rainy': [.4, .7], 
                   'sunny': [.6, .3]
                  }, 
                  index=["rainy", "sunny"])
print df

       rainy  sunny
rainy    0.4    0.6
sunny    0.7    0.3


 transiaiton probabilitys after 1 transition

In [2]:
#for two transitions
print df.dot(df)

       rainy  sunny
rainy   0.58   0.42
sunny   0.49   0.51


In [3]:
from numpy import linalg as LA

In [4]:
LA.matrix_power(df, 2)

array([[ 0.58,  0.42],
       [ 0.49,  0.51]])

In [5]:
LA.matrix_power(df, 5)

array([[ 0.53734,  0.46266],
       [ 0.53977,  0.46023]])

In [6]:
LA.matrix_power(df, 10)

array([[ 0.53846426,  0.46153574],
       [ 0.53845836,  0.46154164]])